config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'
  
  root :to => 'pages#home'

  devise_for :accounts, controllers: { sessions: "accounts/sessions", registrations: "accounts/registrations", passwords: "accounts/passwords" }
  
  resources :polls, only: %i[index show new create]
  resources :votes, only: %i[create update destroy]

  get "/polls/:id/close", to: "polls#close", as: :close_poll
  get "/polls/:id/open", to: "polls#open", as: :open_poll
end

app/models/poll.rb
class Poll < ApplicationRecord
  belongs_to :account

  has_many :votes, dependent: :destroy

  validates :title, presence: true
  
  validate :check_choices, on: %i[create]

  def owner?(account)
    account.id == self.account_id
  end

  def open?
    self.closed_at.nil? || self.closed_at.to_i > Time.now.to_i
  end

  def count_votes(choice)
    self.votes.where(gmap_id: choice).length
  end

  def percent_votes(choice)
    return 0 if self.votes.count.to_f == 0
    (self.count_votes(choice).to_f / self.votes.count.to_f) * 100.0
  end

  private

  def check_choices
    errors.add(:poll, :choices) if self.choices.split(',').length < 2
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_poll, only: %i[show edit update close open]

  before_action only: %i[close open] do
    raise ActionController::RoutingError.new("Polls : Need poll's owner to change state") unless @poll.owner?(current_account)
  end

  def index
    @polls = {
      opened: current_account.open_polls,
      closed: current_account.close_polls
    }
  end

  def show
    @my_vote = current_account.votes.find_by(poll_id: @poll.id) || Vote.new()
  end

  def new
    @poll = Poll.new()
  end

  def create
    @poll = Poll.new(params_poll)
    @poll.account_id = current_account.id

    return redirect_to polls_path if @poll.save

    @poll.choices = ""
    render :new
  end

  def open
    @poll.update(closed_at: nil)
    redirect_to poll_path(@poll.id)
  end

  def close
    @poll.update(closed_at: Time.now)
    redirect_to poll_path(@poll.id)
  end

  private

  def set_poll 
    @poll = Poll.find(params[:id])
  end

  def params_poll
    params.require(:poll).permit(:title, :description, :choices)
  end
end

app/helpers/polls_helper.rb
module PollsHelper

  def get_vote(id)
    JSON.parse(Net::HTTP.get(URI("https://maps.googleapis.com/maps/api/place/details/json?key=#{ENV['GOOGLE_API_SERVER_KEY']}&place_id=#{id}")))['result']
  end
end

app/views/polls/_close.html.erb
<% poll.choices.split(',').each do |choice| %>
  <div class="mp-vote-radio">
    <%= render "votes/show", vote: get_vote(choice) %>
    <div class="mp-vote-score"><div class="mp-vote-score-progress" style="width:<%= poll.percent_votes(choice) %>%"></div><span><%= poll.percent_votes(choice) %>%</span></div>   
  </div>
<% end %>



<%= link_to "<i class='fas fa-play'></i>".html_safe, open_poll_path(poll), class: "mp-button", data: { tippy_content: "Ouvrir le sondage"}  if poll.owner?(current_account) %>

app/views/polls/_form.html.erb
<%= form_for(poll, html: { class: "mp-form-polls" }, data: { controller: "polls" }) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
    <span class="field-info">Champs requis</span>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, rows: 6, class: "mp-textarea-autosize" %>
  </div>

  
  <div class="field">
    <%= f.label :choices %>
    <%= f.hidden_field :choices, data: { target: "polls.choices", action: "change->polls#show" } %>
    <div id="poll-choices" data-target="polls.content"></div>
    <span class="field-info">Champs requis (min 2, max 5)</span>
  </div>

  <div class="field">
    <div class="mp-flex mp-flex-direction-row">
      <%= text_field_tag :search_places, "", placeholder: "Rechercher un lieu" %>
      <%= button_tag "<i class='fas fa-search'></i>".html_safe, type: "button", class: "mp-button mp-button-search", data: { reflex: "click->PollsReflex#searchPlaces" } %>
    </div>
    <div id="gmap-api" data-simplebar><div id="gmap-api-container"></div></div>
  </div>
  

  <div class="actions">
    <%= f.submit "Enregistrer" %>
  </div>

<% end %>

app/views/polls/_open.html.erb
<%= form_for(vote, data: { controller: "polls"}) do |f| %>
  <%= f.hidden_field :poll_id, value: poll.id %>
  <% poll.choices.split(',').each do |choice| %>
    <div class="mp-vote-radio">
      <%= f.radio_button :gmap_id, choice, checked: (vote.gmap_id == choice) %>
      <%= f.label :"gmap_id_#{choice.downcase }", data: { target: "polls.choices", place_id: choice } do %>
        <%= render "votes/show", vote: get_vote(choice) %>
      <% end %>   
      <div class="mp-vote-score"><div class="mp-vote-score-progress" style="width:<%= poll.percent_votes(choice) %>%"></div><span><%= poll.percent_votes(choice) %>%</span></div>   
    </div>
  <% end %>

  <%= f.submit class: "mp-button-large" %>
<% end %>

<%= link_to "<i class='fas fa-times'></i>".html_safe, close_poll_path(poll), class: "mp-button mp-button-destroy", data: { tippy_content: "Fermer le sondage"} if poll.owner?(current_account) %>

app/views/polls/_preview.html.erb
<%= link_to poll_path(poll) do %>
  <span class="mp-poll-title"><%= poll.title %></span>
  <span class="mp-poll-description"><%= simple_format(poll.description) %></span>
  <span class="mp-poll-infos"><i class="fas fa-info-circle"></i>Créé par <%= poll.account.pseudo %> le <%= poll.created_at %></span>
  <span class="mp-poll-votes"><i class="fas fa-vote-yea"></i>Nombre de votes <%= poll.votes.count %><%= " - [VOTE TERMINÉ] " unless poll.open? %></span>
<% end %>

app/views/polls/index.html.erb
<h1>Mes sondages</h1>

<%= link_to "<i class='fas fa-plus'></i>".html_safe, new_poll_path, class: "mp-button", data: { tippy_content: "Créer un sondage" } %>

<%= content_tag :section, class: "mp-cards" do %>
  <h2>Mes sondages en cours</h2>

  <ul>
    <% @polls[:opened].each do |poll| %>
      <li><%= render "preview", poll: poll %></li>
    <% end %>
  </ul>
<% end unless @polls[:opened].empty? %>

<%= content_tag :section, class: "mp-cards" do %>
  <h2>Mes sondages terminés</h2>

  <ul>
    <% @polls[:closed].each do |poll| %>
      <li><%= render "preview", poll: poll %></li>
    <% end %>
  </ul>
<% end unless @polls[:closed].empty? %>

app/views/polls/new.html.erb
<h1>Nouveau sondage</h1>

<%= render "form", poll: @poll %>

app/views/polls/show.html.erb
<h2><%= @poll.title %></h2>
<p><%= @poll.description %></p>


<%= render "#{@poll.open? ? "open" : "close"}", poll: @poll, vote: @my_vote %>