config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'
  
  root :to => 'pages#home'

  devise_for :accounts, controllers: { sessions: "accounts/sessions", registrations: "accounts/registrations", passwords: "accounts/passwords" }
  
  resources :polls, only: %i[index show new create]
  resources :votes, only: %i[create update destroy]

  get "/polls/:id/close", to: "polls#close", as: :close_poll
  get "/polls/:id/open", to: "polls#open", as: :open_poll
end

app/views/layouts/_gmap.html.erb
<%= content_tag :ul, class: "gmap-api-items" do %>
  <% results.each do |result| %>    
    <%= content_tag :li, id: result['place_id'] do %>
      <%= button_tag type: "button", data: { action: "click->polls#new" } do %>
        <figure>
          <% begin %>
            <%= image_tag "https://maps.googleapis.com/maps/api/place/photo?key=#{ENV['GOOGLE_API_SERVER_KEY']}&photoreference=#{result["photos"][0]["photo_reference"]}&maxheight=120" %>
          <% rescue; end %>
        </figure>
        <div class="mp-flex mp-flex-direction-column mp-flex-justify-center mp-flex-1">
          <span class="gmap-item-name"><%= result['name'] %></span>
          <div class="mp-flex mp-flex-direction-row">
            <span class="gmap-item-rating"><i class="fas fa-star"></i><%= result['rating'] %></span>
            <span class="gmap-item-address"><%= result['formatted_address'] %></span>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
<% end if results.length > 0 %>

app/views/layouts/_navbar.html.erb
<nav id="navigation">
  <%= link_to root_url, id:"navigation-brand" do %>
    <%= image_tag "arkasy.png", alt:"brand" %>
  <% end %>

  <div id="navigation-pseudo"><%= current_account.pseudo %></div>

  <div id="navigation-panel">
    <%= link_to "<i class='fas fa-poll'></i>".html_safe, polls_path, class: "mp-button", data: { tippy_content: "Sondages", tippy_placement: 'bottom' } %>
    <%= link_to "<i class='fas fa-cog'></i>".html_safe, edit_account_registration_path, class: "mp-button", data: { tippy_content: "Paramètres", tippy_placement: 'bottom' } %>
    <%= link_to "<i class='fas fa-sign-out-alt'></i>".html_safe, destroy_account_session_path, class: "mp-button mp-button-logout", data: { turbolinks: "false", tippy_content: "Déconnexion", tippy_placement: 'bottom' }, :method => :delete %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiamPoll</title>
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0">
    <meta name="turbolinks-root" content="/">
    <meta name="turbolinks-cache-control" content="no-cache">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= javascript_pack_tag 'application', data: { turbolinks_track: 'reload' }, async: true %>
    <%= stylesheet_pack_tag 'application', media: 'all', data: { turbolinks_track: 'reload' } %>
  </head>

  <body data-controller="application" >
    <%= render "layouts/navbar" if account_signed_in? %>    
    <main><div class="mp-row"><%= yield %></div></main>
  </body>
</html>